### ISSUE TITLE
Не работает на линуксе

### ISSUE THREAD

**Issue by RTXGalwet** [Haloger7/helloworld-fasm#1]
https://i.imgur.com/x8YALAF.png
Даже не собралось 😭

**Comment by Haloger7** [comment]
На винде все ок, а как ты фасм ставил?

**Comment by RTXGalwet** [comment]
```
sudo pacman -S fasm
```
Кстати, где ты win32a.inc на линуксе нашел? По названию похоже что эта хуета ток на винде есть 😱

**Comment by Haloger7** [comment]
Да блин я на винде делал

**Comment by RTXGalwet** [comment]
Ну чини на линукс
